### ISSUE TITLE
Strange result - union of 2 triangles gives 7 segments, but no regions when constructing Polygon

### ISSUE THREAD

**Issue by caywen** [idormenco/PolyBool.Net#2]
Here is a case I don't understand. I have 2 triangles that intersect. When I do a union, I get 0 regions in the resulting polygon. That doesn't seem right. Perhaps I am using the library wrong?

            {
                var p1 = new Polybool.Net.Objects.Polygon {
                    Regions = new List<Polybool.Net.Objects.Region> {
                        new Polybool.Net.Objects.Region {
                            Points = new List<Polybool.Net.Objects.Point> {
                                new Polybool.Net.Objects.Point(41, 9),
                                new Polybool.Net.Objects.Point(31, 21),
                                new Polybool.Net.Objects.Point(53, 14)
                            }
                        }
                    }
                };
                var p2 = new Polybool.Net.Objects.Polygon {
                    Regions = new List<Polybool.Net.Objects.Region> {
                        new Polybool.Net.Objects.Region {
                            Points = new List<Polybool.Net.Objects.Point> {
                                new Polybool.Net.Objects.Point(42, 13),
                                new Polybool.Net.Objects.Point(40, 22),
                                new Polybool.Net.Objects.Point(47, 20)
                            }
                        }
                    }
                };

                var seg1 = Polybool.Net.Logic.PolyBool.Segments(p1);
                var seg2 = Polybool.Net.Logic.PolyBool.Segments(p2);
                var c = Polybool.Net.Logic.PolyBool.Combine(seg1, seg2);
                var segs = new Polybool.Net.Objects.PolySegments {
                    Segments = Polybool.Net.Logic.SegmentSelector.Union(c.Combined)
                };
                
                var u = Polybool.Net.Logic.PolyBool.Polygon(segs);
                // u has 0 regions for union? segs has 8 segments
            }

**Comment by caywen** [comment]
Simplified case:

            {
                var p1 = new Polybool.Net.Objects.Polygon {
                    Regions = new List<Polybool.Net.Objects.Region> {
                        new Polybool.Net.Objects.Region {
                            Points = new List<Polybool.Net.Objects.Point> {
                                new Polybool.Net.Objects.Point(0, 0),
                                new Polybool.Net.Objects.Point(16, 0),
                                new Polybool.Net.Objects.Point(8, 8)
                            }
                        }
                    }
                };
                var p2 = new Polybool.Net.Objects.Polygon {
                    Regions = new List<Polybool.Net.Objects.Region> {
                        new Polybool.Net.Objects.Region {
                            Points = new List<Polybool.Net.Objects.Point> {
                                new Polybool.Net.Objects.Point(16, 6),
                                new Polybool.Net.Objects.Point(8, 14),
                                new Polybool.Net.Objects.Point(0, 6),
                            }
                        }
                    }
                };

                var seg1 = Polybool.Net.Logic.PolyBool.Segments(p1);
                var seg2 = Polybool.Net.Logic.PolyBool.Segments(p2);
                var c = Polybool.Net.Logic.PolyBool.Combine(seg1, seg2);
                var segs = new Polybool.Net.Objects.PolySegments {
                    Segments = Polybool.Net.Logic.SegmentSelector.Union(c.Combined)
                };
                
                for (int i = 0; i < segs.Segments.Count; i++) {
                    var s = segs.Segments[i];
                    Console.WriteLine("Segment {0} : {1},{2} -> {3},{4}", i,
                        s.Start.X, s.Start.Y, s.End.X, s.End.Y);
                }
                var u = Polybool.Net.Logic.PolyBool.Polygon(segs);
            }

There seems to be a problem with the segment chainer. The segments are as follows:

Segment 0 : 0,0 -> 6.000,6.000
Segment 1 : 0,6 -> 6.000,6.000
Segment 2 : 0,6 -> 8,14
Segment 3 : 0,0 -> 16,0
Segment 4 : 10.000,6.000 -> 16,0
Segment 5 : 10.000,6.000 -> 16,6
Segment 6 : 8,14 -> 16,6

These form a closed polygon. But the segment chainer never seems to think so, and thus returns 0 regions. Curious..

**Comment by caywen** [comment]
The 2 triangles look as follows:
![image](https://user-images.githubusercontent.com/1766966/104873821-3cd1f280-5906-11eb-8645-d703cdde7baf.png)

**Comment by idormenco** [comment]
@caywen thanks a lot for reporting this issue. I will try to investigate this and come back with a solution ASAP

**Comment by idormenco** [comment]
@caywen you were right, I fixed this issue and I will publish new dlls.
Also I wanted to improve usability and make it less error prone so now you can call
```
Polygon unified = SegmentSelector.Union(p1, p2); // p1 and p2 are polygons as well.
```
see the released version here https://www.nuget.org/packages/Polybool.Net/
Thanks again for spotting this issue.

**Comment by caywen** [comment]
Thank you so much! I'll check out the new release.
